# Generated by Django 5.1.3 on 2024-11-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_employee_salary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payroll",
            name="net_salary",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
